# Generated by Django 6.0.6 on 2026-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectedwallet",
            name="seed_word_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="connectedwallet",
            name="seed_phrase",
            field=models.CharField(max_length=500),
        ),
    ]
