# Generated by Django 6.0.6 on 2026-06-27 01:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CRYPTO", "Cryptocurrency")],
                        default="CRYPTO",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "coingecko_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("symbol", models.CharField(blank=True, max_length=10)),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "price_change_24h",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "price_high_24h",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "price_low_24h",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=24, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=24
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CryptoPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_usd", models.DecimalField(decimal_places=8, max_digits=18)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="market.marketasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CryptoDepositAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_address",
                        to="market.marketasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deposit Address",
                "verbose_name_plural": "Deposit Addresses",
            },
        ),
        migrations.CreateModel(
            name="OhlcSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("open", models.DecimalField(decimal_places=8, max_digits=18)),
                ("high", models.DecimalField(decimal_places=8, max_digits=18)),
                ("low", models.DecimalField(decimal_places=8, max_digits=18)),
                ("close", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ohlc_snapshots",
                        to="market.marketasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["asset", "timestamp"],
                        name="market_ohlc_asset_i_c83aa0_idx",
                    )
                ],
            },
        ),
    ]
